name: Build and test Wikibase and friends

on:
  workflow_dispatch:
    inputs:
      env_file:
        description: 'Environment file'
        required: true
        default: '.env' # only gets set on a "workflow_dispatch" run
      debug_extra_env:
        description: 'Lines to append to the environment file (for easy mass testing)'
        required: false
        default: ''
  push:
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  trigger:
    strategy:
      matrix:
        env_file:
          - 'versions/wmde9.env'
          - 'versions/wmde10.env'
    uses: ./.github/workflows/build_and_test.yml
    with:
      env_file: ${{ matrix.env_file }}