name: Build and test Wikibase and friends

on:
  push:
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  trigger:
    strategy:
      fail-fast: false
      matrix:
        include:
          # TODO add latest once wmde.11 (and the fixes there) are merged in https://github.com/wmde/wikibase-release-pipeline/pull/398
          # Running wmde11 and wmde10 at the same time might require changes to some of the files altered in that PR...
          # - env_file: 'versions/latest.env'
          #   upgrade_from: [ 'wmde.9', 'wmde.10' ] # 1.37 and 1.38
          - version: 'wmde.12' # 1.39
            upgrade_from: [ 'wmde.9', 'wmde.10' ] # 1.37 and 1.38. Could add the previous 1.39? (wmde.11)
          - version: 'wmde.11' # 1.39
            upgrade_from: [ 'wmde.9', 'wmde.10' ] # 1.37 and 1.38
          - version: 'wmde.10' # 1.38
            upgrade_from: [ 'wmde.9' ] # 1.36 and 1.37. Could add 1.36 (wmde.8) if we re added old files
    uses: ./.github/workflows/build_and_test.yml
    with:
      version: ${{ matrix.version }}
      upgrade_from_json: ${{ toJson(matrix.upgrade_from) }}