name: Build and test Wikibase and friends

on:
  workflow_dispatch:
    inputs:
      env_file:
        description: 'Environment file'
        required: true
        default: '.env' # only gets set on a "workflow_dispatch" run
      debug_extra_env:
        description: 'Lines to append to the environment file (for easy mass testing)'
        required: false
        default: ''
  push:
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  trigger:
    strategy:
      matrix:
        include:
          # TODO add latest once wmde.11 (and the fixes there) are merged in https://github.com/wmde/wikibase-release-pipeline/pull/398
          # Running wmde11 and wmde10 at the same time might require changes to some of the files altered in that PR...
          # - env_file: 'versions/latest.env'
          #   upgrade_from: [ 'wmde.9', 'wmde.10' ] # 1.37 and 1.38
          - version: 'wmde.12' # 1.39
          #  upgrade_from: [ 'wmde.9', 'wmde.10', 'wmde.11' ] # 1.37, 1.38 and the previous 1.39
          - version: 'wmde.11' # 1.39
          #  upgrade_from: [ 'wmde.9', 'wmde.10' ] # 1.37 and 1.38
          - version: 'wmde.10' # 1.38
          #  upgrade_from: [ 'wmde.8', 'wmde.9' ] # 1.36 and 1.37
    uses: ./.github/workflows/build_and_test.yml
    with:
      version: ${{ matrix.version }}