name: Test Example

on:
  push:
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  test_example:
    runs-on: ubuntu-latest
    timeout-minutes: 36
    steps:
      - uses: actions/checkout@v3

      - name: Test example
        uses: nick-fields/retry@v2
        with:
          # This step should only take ~10 mins at most to complete, but sometimes locks up
          timeout_minutes: 12
          max_attempts: 3
          retry_on: timeout
          command: make test-example SUITE=example
      
      - name: Archive test example artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: TestExampleArtifacts
          if-no-files-found: error
          path: |
            example/log
            test/log
          